[phases.setup]
nixPkgs = ['python38', 'gcc']

[phases.build]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt']

[start]
cmd = "uvicorn app:app --reload"